### ISSUE TITLE
when to public souce code

### ISSUE THREAD

**Issue by lcssucre** [HKUST-Aerial-Robotics/G3Reg#1]
Great job, when to public souce code

**Comment by qiaozhijian** [comment]
Once the paper is accepted, I intend to make it publicly available. I anticipate that this will take approximately one~two months if reviewers agreed to my response.

**Comment by arminkmbr** [comment]
hi, is there any update to making the code public?

**Comment by qiaozhijian** [comment]
> hi, is there any update to making the code public?

I'm sorry not. I hope it will be released next month. Thank you for your attention.
