### ISSUE TITLE
About runtime error when run demo_seg

### ISSUE THREAD

**Issue by Dlmyoung** [HKUST-Aerial-Robotics/G3Reg#10]
Thanks for your amazing work.During my attempt to reproduce your code,I can compile it fine.

- But when I run `. /bin/demo_seg configs/apollo_lc_bm/gem_pagor.yaml examples/data/velodyne/source.pcd`, it flashes back and says `demo_seg: .... /... /src/xcb_io.c:260: poll_for_event: Assertion !xcb_xlib_threads_sequence_lost' failed,` and sometimes it shows ` Segmentation fault (Address not mapped to object [0x7f02800ee000]).`

**Comment by qiaozhijian** [comment]
Thank you. Pull the origin/master to the local branch and try this https://github.com/HKUST-Aerial-Robotics/G3Reg/blob/51e84d39ee884e89b3fa6a4e246e31c7ea84dcaf/docs/demo.md?plain=1#L8

**Comment by Dlmyoung** [comment]
Thank you for your prompt and effective response!！
