### ISSUE TITLE
Possibility on cross-source point cloud registration between pedestrain and vehicle

### ISSUE THREAD

**Issue by zhh2005757** [HKUST-Aerial-Robotics/G3Reg#12]
Hi author, thanks for opening such a great work. I am curious about whether G3Reg can be used for cross-source point cloud registration such as pedestrain and vehicle, since the point clouds from pedestrains are not stationary as much as those from vehicles. Can author share more ideas about this scenario? Thanks a lot!

**Comment by qiaozhijian** [comment]
Hi, do you mean registering pedestrain and vehicle or scene point clouds containing pedestrain and vehicles? If the former, G3Reg can't since they are different objects. If the last, it can because the ped and vehicles will be regarded as outliers if they don't obey rigid transformation constraints.

**Comment by qiaozhijian** [comment]
I think you can have a try. There are some tricks that may improve performance. For example, use IMU to align the frame with the gravity; modify the hyperparameters of TRAVEL or DCVC (the segmentation method we used in this method)

**Comment by zhh2005757** [comment]
Okay I plan to try it later. BTW have you ever  handled some scenarios like this before?

**Comment by qiaozhijian** [comment]
No, but I think it's not a very challenging issue, especially when you use the same LiDAR type. BTW, which type do you use?

**Comment by zhh2005757** [comment]
> No, but I think it's not a very challenging issue, especially when you use the same LiDAR type. BTW, which type do you use?

I use ouster LiDAR, but I found it unstable to use scan context and icp for registration in fact, the reason lies on that the changing lidar fov of helmet influences parameters of above methods seriously and it is hard to find one suitable case.

**Comment by zhh2005757** [comment]
> OK, besides my method, try this one as well. https://github.com/sparolab/solid

Great!. I will test both your work and this work. Thanks for your advice!
