### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by yuafowo** [HKUST-Aerial-Robotics/G3Reg#4]
I encountered this problem when compiling:
 "In file included from /ws_livox/src/G3Reg-main/Thirdparty/robot_utils/include/nanoflann/KDTreeVectorOfVectorsAdaptor.h:31:0,
                 from /ws_livox/src/G3Reg-main/src/back_end/pagor/geo_verify.cpp:8:
/ws_livox/src/G3Reg-main/Thirdparty/robot_utils/include/nanoflann/nanoflann.hpp:47:10: fatal error: ../../../../../../../../../../usr/include/c++/9/algorithm: No such file or directory
 #include "../../../../../../../../../../usr/include/c++/9/algorithm"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/g3reg.dir/build.make:89: recipe for target 'CMakeFiles/g3reg.dir/src/back_end/pagor/geo_verify.cpp.o' failed
make[2]: *** [CMakeFiles/g3reg.dir/src/back_end/pagor/geo_verify.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....". 
 I think there is something wrong with the header file reference of this file: "G3Reg\Thirdparty\robot_utils\src\file_manager.cpp"

**Comment by qiaozhijian** [comment]
Thanks for trying G3Reg. I have push new modifications. Please try again.

**Comment by yuafowo** [comment]
> Thanks for trying G3Reg. I have push new modifications. Please try again.

Thanks for your great work, I have successfully run G3Reg.
