### ISSUE TITLE
How to visualize the ellipsoid like demo vedio? have you try the performance in livox mid 360?

### ISSUE THREAD

**Issue by GOD-VV** [HKUST-Aerial-Robotics/G3Reg#7]

**Comment by qiaozhijian** [comment]
Use rviz markers. I have not.

**Comment by qiaozhijian** [comment]
If you have interests, you can have a try of horizon parameters directly. If it doesn't work, feel free to update this issue. A suggestion: debug use demo_seg to check the segmentation at first.

**Comment by GOD-VV** [comment]
Thank you very much! Great work!
